import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-webhook-secret',
}

function formatAssemblyAITranscript(data: any): string {
  if (data.utterances && data.utterances.length > 0) {
    return data.utterances
      .map((u: any) => `[Locutor ${u.speaker}]: ${u.text}`)
      .join('\n')
  }
  return data.text || ''
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  // Validate webhook secret
  const webhookSecret = req.headers.get('x-webhook-secret')
  const expectedSecret = Deno.env.get('ASSEMBLYAI_WEBHOOK_SECRET') || 'agata-webhook-secret'
  if (webhookSecret !== expectedSecret) {
    console.error('[Webhook] Invalid secret:', webhookSecret)
    return new Response('Unauthorized', { status: 401 })
  }

  const body = await req.json()
  const { transcript_id, status } = body

  console.log(`[AssemblyAI Webhook] transcript_id=${transcript_id} status=${status}`)

  if (!transcript_id) {
    return new Response('Missing transcript_id', { status: 400 })
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  const assemblyApiKey = Deno.env.get('ASSEMBLYAI_API_KEY')!
  const supabase = createClient(supabaseUrl, supabaseServiceKey)

  // Find the meeting by assemblyTranscriptId
  const { data: meeting, error: meetingError } = await supabase
    .from('Meeting')
    .select('id, userId, "cloudStoragePath"')
    .eq('assemblyTranscriptId', transcript_id)
    .maybeSingle()

  if (meetingError || !meeting) {
    console.error('[Webhook] Meeting not found for transcript_id:', transcript_id)
    return new Response('Meeting not found', { status: 404 })
  }

  const meetingId = meeting.id

  if (status === 'error') {
    console.error(`[Webhook] AssemblyAI error for meeting ${meetingId}`)
    await supabase.from('Meeting').update({
      assemblyTranscriptId: null,
      status: 'failed',
      errorMessage: 'AssemblyAI falhou — tente novamente para usar Gemini',
      updatedAt: new Date().toISOString(),
    }).eq('id', meetingId)
    await supabase.channel('meeting-status').send({
      type: 'broadcast',
      event: 'transcription_update',
      payload: { meetingId, status: 'failed' },
    })
    return new Response('ok')
  }

  if (status !== 'completed') {
    // AssemblyAI may send intermediate webhooks (queued, processing)
    console.log(`[Webhook] Status ${status} — ignoring`)
    return new Response('ok')
  }

  // Fetch full transcript with utterances from AssemblyAI
  const transcriptRes = await fetch(
    `https://api.assemblyai.com/v2/transcript/${transcript_id}`,
    { headers: { 'Authorization': assemblyApiKey } }
  )

  if (!transcriptRes.ok) {
    const err = await transcriptRes.text()
    console.error('[Webhook] Failed to fetch transcript:', err)
    await supabase.from('Meeting').update({
      status: 'failed',
      errorMessage: `Falha ao buscar transcrição: ${transcriptRes.status}`,
      updatedAt: new Date().toISOString(),
    }).eq('id', meetingId)
    await supabase.channel('meeting-status').send({
      type: 'broadcast',
      event: 'transcription_update',
      payload: { meetingId, status: 'failed' },
    })
    return new Response('ok')
  }

  const transcriptData = await transcriptRes.json()
  const fullTranscriptionText = formatAssemblyAITranscript(transcriptData)
  const realDurationSeconds = transcriptData.audio_duration
    ? Math.round(transcriptData.audio_duration / 1000)
    : 0
  const actualMinutes = Math.max(1, Math.ceil(realDurationSeconds / 60))

  // AssemblyAI transcripts don't include ## Resumo — generated by generate-summary
  const transcription = fullTranscriptionText
  const summary = null
  const actionItems: string[] = []

  await supabase.from('Meeting').update({
    status: 'completed',
    transcription,
    summary,
    actionItems,
    assemblyTranscriptId: null,
    fileDuration: realDurationSeconds > 0 ? realDurationSeconds : null,
    updatedAt: new Date().toISOString(),
  }).eq('id', meetingId)

  // Update usage counter
  const currentMonth = new Date().toISOString().slice(0, 7)
  const { data: existingUsage } = await supabase
    .from('Usage')
    .select('id, transcriptionsUsed, totalMinutesTranscribed, currentMonth')
    .eq('userId', meeting.userId)
    .maybeSingle()

  if (existingUsage) {
    if (existingUsage.currentMonth === currentMonth) {
      await supabase.from('Usage').update({
        transcriptionsUsed: (existingUsage.transcriptionsUsed || 0) + 1,
        totalMinutesTranscribed: (existingUsage.totalMinutesTranscribed || 0) + actualMinutes,
        updatedAt: new Date().toISOString(),
      }).eq('id', existingUsage.id)
    } else {
      await supabase.from('Usage').update({
        transcriptionsUsed: 1,
        totalMinutesTranscribed: actualMinutes,
        currentMonth,
        updatedAt: new Date().toISOString(),
      }).eq('id', existingUsage.id)
    }
  } else {
    await supabase.from('Usage').insert({
      userId: meeting.userId,
      transcriptionsUsed: 1,
      currentMonth,
      totalMinutesTranscribed: actualMinutes,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    })
  }

  // Log to TranscriptionLog
  try {
    await supabase.from('TranscriptionLog').insert({
      meetingId,
      userId: meeting.userId,
      provider: 'assemblyai',
      durationSecs: realDurationSeconds,
      fileSizeBytes: 0,
      chunks: 1,
      costCents: 0,
      success: true,
      createdAt: new Date().toISOString(),
    })
  } catch (logErr) {
    console.error('[Webhook] TranscriptionLog insert failed:', logErr)
  }

  // Send completion email
  try {
    const { data: userData } = await supabase
      .from('User').select('email, name').eq('id', meeting.userId).maybeSingle()
    const { data: meetingInfo } = await supabase
      .from('Meeting').select('title').eq('id', meetingId).maybeSingle()
    if (userData) {
      await supabase.functions.invoke('send-email', {
        body: {
          type: 'transcription_done',
          to: userData.email,
          data: {
            name: userData.name || 'Usuário',
            meetingTitle: meetingInfo?.title || 'Reunião',
            meetingId,
          }
        }
      })
    }
  } catch (emailErr) {
    console.error('[Webhook] Email error:', emailErr)
  }

  // Broadcast completion to frontend
  await supabase.channel('meeting-status').send({
    type: 'broadcast',
    event: 'transcription_update',
    payload: { meetingId, status: 'completed' },
  })

  // Fire-and-forget: generate embeddings for semantic search
  supabase.functions
    .invoke('generate-embeddings', {
      body: { meetingId, userId: meeting.userId },
    })
    .catch((e: unknown) => console.error('[Webhook] Embeddings error:', e))

  console.log(`[AssemblyAI Webhook] ✅ Meeting ${meetingId} completed`)
  return new Response(JSON.stringify({ success: true }), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  })
})
