// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hblczvmpyaznbxvdcaze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibGN6dm1weWF6bmJ4dmRjYXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDM1MTcsImV4cCI6MjA5MDYxOTUxN30.MdN0KbyehAJDIhO6Dxj_z6G1M6MToZCoMSnqsCL3Tws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});